import type { BallStats } from '../models/types';

export const BALL_PRESETS: BallStats[] = [
  {
    name: 'Heavy Tank',
    radius: 30,
    mass: 5.0,
    maxSpeed: 3.0,
    friction: 0.20,
    restitution: 0.3,
    spinSpeed: 1.0,
    durability: 150,
    attackPower: 80,
    knockbackPower: 100,
    color: '#EE8888',
    icon: '🛡️',
  },
  {
    name: 'Speed Striker',
    radius: 20,
    mass: 1.2,
    maxSpeed: 8.0,
    friction: 0.10,
    restitution: 0.5,
    spinSpeed: 4.0,
    durability: 60,
    attackPower: 50,
    knockbackPower: 30,
    color: '#88EE88',
    icon: '⚡',
  },
  {
    name: 'Balanced Duo',
    radius: 25,
    mass: 3.0,
    maxSpeed: 5.0,
    friction: 0.15,
    restitution: 0.4,
    spinSpeed: 2.5,
    durability: 100,
    attackPower: 60,
    knockbackPower: 60,
    color: '#8888EE',
    icon: '⚖️',
  },
  {
    name: 'Chaos Orb',
    radius: 22,
    mass: 2.5,
    maxSpeed: 6.0,
    friction: 0.10,
    restitution: 0.5,
    spinSpeed: 3.5,
    durability: 80,
    attackPower: 70,
    knockbackPower: 40,
    color: '#EEEE88',
    icon: '🌀',
  },
  {
    name: 'Glass Cannon',
    radius: 18,
    mass: 1.0,
    maxSpeed: 7.0,
    friction: 0.05,
    restitution: 0.6,
    spinSpeed: 5.0,
    durability: 30,
    attackPower: 100,
    knockbackPower: 20,
    color: '#EE88EE',
    icon: '💎',
  },
  {
    name: 'Magnet Core',
    radius: 24,
    mass: 2.8,
    maxSpeed: 4.0,
    friction: 0.10,
    restitution: 0.4,
    spinSpeed: 2.0,
    durability: 90,
    attackPower: 55,
    knockbackPower: 80,
    color: '#88EEEE',
    icon: '🧲',
  },
  {
    name: 'Berserker',
    radius: 26,
    mass: 3.5,
    maxSpeed: 5.5,
    friction: 0.20,
    restitution: 0.4,
    spinSpeed: 2.8,
    durability: 120,
    attackPower: 65,
    knockbackPower: 70,
    color: '#FF9966',
    icon: '🔥',
  },
  {
    name: 'Flurry Blade',
    radius: 21,
    mass: 2.0,
    maxSpeed: 6.5,
    friction: 0.10,
    restitution: 0.5,
    spinSpeed: 4.5,
    durability: 70,
    attackPower: 60,
    knockbackPower: 50,
    color: '#9966FF',
    icon: '🗡️',
  },
];
