import type { BallStats } from '../models/types';

export const BALL_PRESETS: BallStats[] = [
  {
    name: 'Quickstrike',
    radius: 24,
    mass: 2.8,
    maxSpeed: 6.5,
    friction: 0.1,
    restitution: 0.5,
    spinSpeed: 4.5,
    durability: 50,
    attackPower: 2,
    knockbackPower: 35,
    color: '#44CC22',
    icon: '⚡',
    ability: {
      id: 'quickstrike-momentum',
      name: 'Momentum',
      description: 'Each landed hit boosts speed by 50% for 0.8s — keep hitting to maintain the rush.',
      trigger: 'onHitDealt',
      params: {
        statusEffect: 'speedBoost',
        statusTarget: 'self',
        statusDuration: 999999999,
        statusMagnitude: 0.3,
        stackBehavior: 'stack',
        maxStacks: 5,
        statusColor: '#44FF44',
        statusIcon: '⚡',
        hitFlash: true,
        hitFlashColor: '#44FF22',
        hitFlashTarget: 'self',
      },
    },
  },
  {
    name: 'Marksman',
    radius: 24,
    mass: 3.0,
    maxSpeed: 5.0,
    friction: 0.12,
    restitution: 0.45,
    spinSpeed: 3.5,
    durability: 60,
    attackPower: 11,
    knockbackPower: 50,
    color: '#4488CC',
    icon: '🎯',
  },
  {
    name: 'Bloodrage',
    radius: 25,
    mass: 3.0,
    maxSpeed: 5.0,
    friction: 0.15,
    restitution: 0.4,
    spinSpeed: 2.5,
    durability: 70,
    attackPower: 13,
    knockbackPower: 60,
    color: '#CC2200',
    icon: '🔥',
    ability: {
      id: 'bloodrage-fury',
      name: 'Bloodrage',
      description: 'Goes berserk below 30% HP — +50% damage and +40% speed.',
      trigger: 'onLowHP',
      params: {
        threshold: 0.3,
        statusEffect: 'rage',
        statusTarget: 'self',
        statusDuration: 3000,
        statusMagnitude: 0.5,
        stackBehavior: 'refresh',
        maxStacks: 1,
        statusColor: '#FF4400',
        statusIcon: '💢',
        speedBoostDuration: 3000,
        speedBoostMagnitude: 0.7,
        speedBoostColor: '#FF8800',
        speedBoostIcon: '⚡',
        hitFlash: true,
        hitFlashColor: '#CC0000',
        hitFlashTarget: 'self',
      },
    },
  },
];
