import type { BallStats } from '../models/types';
import { ABILITY_PRESETS } from './abilityPresets';

export const BALL_PRESETS: BallStats[] = [
  {
    name: 'Quickstrike',
    radius: 24,
    mass: 2.8,
    maxSpeed: 6.5,
    friction: 0.1,
    restitution: 0.5,
    spinSpeed: 4.5,
    durability: 50,
    attackPower: 2,
    knockbackPower: 35,
    color: '#44CC22',
    icon: '⚡',
    ability: ABILITY_PRESETS['quickstrike-momentum'],
  },
  {
    name: 'Marksman',
    radius: 24,
    mass: 3.0,
    maxSpeed: 5.0,
    friction: 0.12,
    restitution: 0.45,
    spinSpeed: 3.5,
    durability: 60,
    attackPower: 11,
    knockbackPower: 50,
    color: '#4488CC',
    icon: '🎯',
  },
  {
    name: 'Bloodrage',
    radius: 25,
    mass: 3.0,
    maxSpeed: 5.0,
    friction: 0.15,
    restitution: 0.4,
    spinSpeed: 2.5,
    durability: 70,
    attackPower: 13,
    knockbackPower: 60,
    color: '#CC2200',
    icon: '🔥',
    ability: ABILITY_PRESETS['bloodrage-fury'],
  },
];
