import type { WeaponStats } from '../models/types';

export const WEAPON_PRESETS: WeaponStats[] = [
  {
    name: 'Heavy Hammer',
    range: 1.0, speed: 3.0, trigger: 'onCollision',
    description: 'Slow swing; very high knockback on collision.',
    color: '#CC6633',
    attacks: [{ type: 'melee', cooldown: 2.0, damage: 16, knockback: 100 }],
  },
  {
    name: 'Swift Sword',
    range: 1.0, speed: 6.0, trigger: 'onSpeed',
    description: 'Fast slash at top speed; moderate knockback.',
    color: '#66AAFF',
    attacks: [{ type: 'melee', cooldown: 1.0, damage: 10, knockback: 40 }],
  },
  {
    name: 'Long Spear',
    range: 2.0, speed: 4.0, trigger: 'onCollision',
    description: 'Stab with extended reach.',
    color: '#996633',
    attacks: [{ type: 'melee', cooldown: 1.5, damage: 12, knockback: 30 }],
  },
  {
    name: 'Chain Flail',
    range: 2.0, speed: 5.0, trigger: 'onTimer',
    description: 'Spins unpredictably; spawns orbital hitbox every 0.5s.',
    color: '#888888',
    attacks: [{ type: 'melee', cooldown: 0.5, damage: 8, knockback: 40 }],
  },
  {
    name: 'Defender Shield',
    range: 1.0, speed: 0, trigger: 'onCollision',
    description: 'No damage, but reflects enemy hit with 2× knockback.',
    color: '#AAAAFF',
    attacks: [{ type: 'shield', cooldown: 0, damage: 0, knockback: 100 }],
  },
  {
    name: 'Energy Laser',
    range: 10.0, speed: 10.0, trigger: 'onTimer',
    description: 'Fires a fast beam toward the opponent every 3s.',
    color: '#FF4444',
    attacks: [{ type: 'projectile', cooldown: 3.0, damage: 12, knockback: 50, aimAtEnemy: true }],
  },
  {
    name: 'Power Cannon',
    range: 8.0, speed: 5.0, trigger: 'onTimer',
    description: 'Launches a heavy orb; high damage and knockback.',
    color: '#FF8833',
    attacks: [{ type: 'projectile', cooldown: 3.0, damage: 16, knockback: 80, aimAtEnemy: true }],
  },
  {
    name: 'Boomerang',
    range: 6.0, speed: 8.0, trigger: 'onTimer',
    description: 'Throws and returns; can hit twice.',
    color: '#AACC44',
    attacks: [{ type: 'projectile', cooldown: 2.0, damage: 10, knockback: 30, aimAtEnemy: true }],
  },
  {
    name: 'Shockwave',
    range: 3.0, speed: 0, trigger: 'onLowHP',
    description: 'When HP < 30%, emits a radial blast.',
    color: '#FF44FF',
    attacks: [{ type: 'aoe', cooldown: 5.0, damage: 6, knockback: 100 }],
  },
  {
    name: 'Magnet Beam',
    range: 5.0, speed: 0, trigger: 'onCollision',
    description: 'Pulls the opponent closer on hit (no damage).',
    color: '#44FFAA',
    attacks: [{ type: 'utility', cooldown: 1.0, damage: 0, knockback: 0 }],
  },
  {
    name: 'Repulsor',
    range: 3.0, speed: 0, trigger: 'onCollision',
    description: 'Shock-push on impact: strong outward force.',
    color: '#FFFF44',
    attacks: [{ type: 'utility', cooldown: 4.0, damage: 4, knockback: 120 }],
  },
  {
    name: 'Grenade Bomb',
    range: 5.0, speed: 6.0, trigger: 'onTimer',
    description: 'Lobs a bomb that explodes on contact or after 2s.',
    color: '#44AA44',
    attacks: [{ type: 'projectile', cooldown: 4.0, damage: 20, knockback: 100, aimAtEnemy: true }],
  },
];
