import type { WeaponStats } from '../models/types';

export const WEAPON_PRESETS: WeaponStats[] = [
  {
    name: 'Heavy Hammer',
    category: 'melee',
    damage: 80,
    knockback: 100,
    range: 1.0,
    speed: 3.0,
    cooldown: 2.0,
    trigger: 'onCollision',
    description: 'Slow swing; very high knockback on collision.',
    color: '#CC6633',
  },
  {
    name: 'Swift Sword',
    category: 'melee',
    damage: 50,
    knockback: 40,
    range: 1.0,
    speed: 6.0,
    cooldown: 1.0,
    trigger: 'onSpeed',
    description: 'Fast slash at top speed; moderate knockback.',
    color: '#66AAFF',
  },
  {
    name: 'Long Spear',
    category: 'melee',
    damage: 60,
    knockback: 30,
    range: 2.0,
    speed: 4.0,
    cooldown: 1.5,
    trigger: 'onCollision',
    description: 'Stab with extended reach.',
    color: '#996633',
  },
  {
    name: 'Chain Flail',
    category: 'melee',
    damage: 40,
    knockback: 40,
    range: 2.0,
    speed: 5.0,
    cooldown: 0.5,
    trigger: 'onTimer',
    description: 'Spins unpredictably; spawns orbital hitbox every 0.5s.',
    color: '#888888',
  },
  {
    name: 'Defender Shield',
    category: 'shield',
    damage: 0,
    knockback: 100,
    range: 1.0,
    speed: 0,
    cooldown: 0,
    trigger: 'onCollision',
    description: 'No damage, but reflects enemy hit with 2× knockback.',
    color: '#AAAAFF',
  },
  {
    name: 'Energy Laser',
    category: 'projectile',
    damage: 60,
    knockback: 50,
    range: 10.0,
    speed: 10.0,
    cooldown: 3.0,
    trigger: 'onTimer',
    description: 'Fires a fast beam toward the opponent every 3s.',
    color: '#FF4444',
  },
  {
    name: 'Power Cannon',
    category: 'projectile',
    damage: 80,
    knockback: 80,
    range: 8.0,
    speed: 5.0,
    cooldown: 3.0,
    trigger: 'onTimer',
    description: 'Launches a heavy orb; high damage and knockback.',
    color: '#FF8833',
  },
  {
    name: 'Boomerang',
    category: 'projectile',
    damage: 50,
    knockback: 30,
    range: 6.0,
    speed: 8.0,
    cooldown: 2.0,
    trigger: 'onTimer',
    description: 'Throws and returns; can hit twice.',
    color: '#AACC44',
  },
  {
    name: 'Shockwave',
    category: 'aoe',
    damage: 30,
    knockback: 100,
    range: 3.0,
    speed: 0,
    cooldown: 5.0,
    trigger: 'onLowHP',
    description: 'When HP < 30%, emits a radial blast.',
    color: '#FF44FF',
  },
  {
    name: 'Magnet Beam',
    category: 'utility',
    damage: 0,
    knockback: 0,
    range: 5.0,
    speed: 0,
    cooldown: 1.0,
    trigger: 'onCollision',
    description: 'Pulls the opponent closer on hit (no damage).',
    color: '#44FFAA',
  },
  {
    name: 'Repulsor',
    category: 'utility',
    damage: 20,
    knockback: 120,
    range: 3.0,
    speed: 0,
    cooldown: 4.0,
    trigger: 'onCollision',
    description: 'Shock-push on impact: strong outward force.',
    color: '#FFFF44',
  },
  {
    name: 'Grenade Bomb',
    category: 'projectile',
    damage: 100,
    knockback: 100,
    range: 5.0,
    speed: 6.0,
    cooldown: 4.0,
    trigger: 'onTimer',
    description: 'Lobs a bomb that explodes on contact or after 2s.',
    color: '#44AA44',
  },
];
